# Generated by Django 5.0.4 on 2024-05-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_vote_choice_text_alter_vote_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
